---
experiments:
  metero_use: ['2m_temperature',
               'boundary_layer_height',  # Comment out for no_BPL experiments.
               'k_index',
               'relative_humidity+950',
               'surface_pressure',
               'total_precipitation',
               'u_component_of_wind+950',
               'v_component_of_wind+950',]
  save_npy: True
  dataset_num: 3
  model: PM25_GNN_nosub
#  model: LSTM
#  model: GRU
#  model: GC_LSTM
#  model: nodesFC_GRU
#  model: PM25_GNN
#  model: PM25_GNN_nosub

train:
  batch_size: 32
  epochs: 50
  exp_repeat: 10
  hist_len: 2
  pred_len: 24
  weight_decay: 0.0005
  early_stop: 10
  lr: 0.0005

filepath:
 I1dbbc952ac002019b3:
    knowair_fp: /root/pm25/data/KnowAir.npy
    results_dir: /root/pm25/results

data:
  metero_var:
    ['100m_u_component_of_wind',
     '100m_v_component_of_wind',
     '2m_dewpoint_temperature',
     '2m_temperature',
     'boundary_layer_height',
     'k_index',
     'relative_humidity+950',
     'relative_humidity+975',
     'specific_humidity+950',
     'surface_pressure',
     'temperature+925',
     'temperature+950',
     'total_precipitation',
     'u_component_of_wind+950',
     'v_component_of_wind+950',
     'vertical_velocity+950',
     'vorticity+950']
Transformer:
  seq_len: 96  # input sequence length
  label_len: 48  # start token length
  pred_len: 96
  d_model: 512
  n_heads: 8
  e_layers: 2
  d_layers: 1
  d_ff: 2048
  dropout: 0.1
  activation: "gelu"
  embedding: "timeF"  # from embed
  channel_independence: false
  inverse: false
  class_strategy: "projection"
  efficient_training: false
  use_norm: true
  freq: "h"
  enc_in: 7
  dec_in: 7
  c_out: 7
  moving_avg: 25
dataset:
  data_start: [[2015, 1, 1, 0, 0], GMT]
  data_end: [[2018, 12, 31, 21, 0], GMT]

  1:
    train_start: [[2015, 1, 1], GMT]
    train_end: [[2016, 12, 31], GMT]
    val_start: [[2017, 1, 1], GMT]
    val_end: [[2017, 12, 31], GMT]
    test_start: [[2018, 1, 1], GMT]
    test_end: [[2018, 12, 31], GMT]

  2:
    train_start: [[2015, 11, 1], GMT]
    train_end: [[2016, 2, 28], GMT]
    val_start: [[2016, 11, 1], GMT]
    val_end: [[2017, 2, 28], GMT]
    test_start: [[2017, 11, 1], GMT]
    test_end: [[2018, 2, 28], GMT]

  3:
    train_start: [[2016, 9, 1], GMT]
    train_end: [[2016, 11, 30], GMT]
    val_start: [[2016, 12, 1], GMT]
    val_end: [[2016, 12, 31], GMT]
    test_start: [[2017, 1, 1], GMT]
    test_end: [[2017, 1, 31], GMT]
